name: learn-github-action
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules # node_modules 가 변했는지 확인
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies # 변했으면 npm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Test # 테스트
        run: npm run test a
  