name: learn-github-action
on: 
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies    # 의존 파일 설치
        run: npm install

      - name: Test
        run: npm run test
  