name: learn-github-action
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        run: 
          npm install
      - name: npm test
        run: 
          npm test
  